---
- hosts: os_linux
  gather_facts: true
  tasks:
  
  - name: Print all avaliable facts
    ansible.builtin.debug:
      var: ansible_facts 
    
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_mounts
  
  - name: Extract drive information
    set_fact:
      drive_information: "{% set output = [] %}\
          {{ output.append((ansible_mounts | selectattr('mount','equalto','/') | list | first).size_total/1024|pow(3)) }}\
          {{ output.append((ansible_mounts | selectattr('mount','equalto','/') | list | first).size_available/1024|pow(3)) }}\
          {{ output.append(ansible_facts.memtotal_mb/1024) }}\
          {{ output.append(ansible_facts.memfree_mb/1024) }}\
          {{ output.append(ansible_facts.swaptotal_mb/1024) }}\
          {{ output.append(ansible_facts.swapfree_mb/1024) }}\
          {{ output }}"
  - debug:
      var: drive_information

  - name: create CSV file
    delegate_to: localhost
    become: false
    template:
      src: linformation.j2
      dest: ~/ansible/toolbox/linformation.csv

  - name: launch python script
    delegate_to: localhost
    run_once: true
    ansible.builtin.script: /home/clay/ansible/toolbox/linformation.py /home/clay/ansible/toolbox/linformation.csv
    register: script_output

  - name: output script
    ansible.builtin.debug:
      var: script_output.stdout_lines
