- name: Query customer data from the database
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../path
    - ../path
  tasks:

  - name: Query Database
    community.mysql.mysql_query:
      login_host: host 
      login_user: "user"
      login_password: "password"
      login_port: "port"
      login_db: db
      query: "query"
    register: customer_data

  - name: Extract customer data from query
    set_fact:
      customer_information: "{% set output = [] %}\
          {% for row in customer_data.query_result %}\
            {% for customer in row %}\
              {{ output.append(customer.value1) }}\
              {{ output.append(customer.value2) }}\
            {% endfor %}\
          {% endfor %}\
          {{ output }}"

  - name: Write customer data to CSV file
    copy:
      content: "{{ customer_information }}"
      dest: "~/dest/path"

  - name: send email via sendgrid
    community.general.sendgrid:
      api_key: "---"
      from_address: "---"
      to_addresses:
        - "---"
      bcc:
        - "---"
        - "---"
      subject: "UK Customer report"
      body: "Here is a list of UK based customers."
      attachments:
        - "~/dest/path"

