---
- name: Configure swapfile
  hosts: os_linux
  gather_facts: false
  become: yes
  tasks:

  - name: Turn off current swap file
    command: swapoff /swapfile
    tags:
      - delete

  - name: Remove swap file
    command: rm /swapfile
    tags:
      - delete

  - name: Create swap file
    command: fallocate -l {{size}}G /swapfile
    tags:
      - provision

  - name: Change swap file permissions
    file: path="/swapfile"
            mode=0600
    tags:
      - provision

  - name: Format swap file
    command: mkswap /swapfile
    tags:
      - provision

  - name: Turn on swap
    command: swapon /swapfile
    tags:
      - provision

  - name: Display memory
    command: free -m
    register: memory_allocation
    tags:
      - status

  - debug:
      var: memory_allocation.stdout_lines
    tags:
      - status

  - name: Display disk
    command: df -h
    register: space_allocation
    tags:
      - status

  - debug:
      var: space_allocation.stdout_lines
    tags:
      - status
               
